[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "rs-object"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version= "1", features=["serde-json"]}
napi-derive = "1"
object = "0.27"
anyhow = "1"
serde_json="1"
serde="1"
serde_derive="1"

[target.'cfg(all(any(windows, unix), target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
